
name: Laravel Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_CONNECTION: pgsql
      DB_HOST: 127.0.0.1 # Use service name as host
      DB_DATABASE: laravel_test
      DB_USERNAME: postgres
      DB_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      REDIS_HOST: 127.0.0.1
      REDIS_PASSWORD: null
      REDIS_PORT: 6379

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: laravel_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, intl, pdo, pdo_pgsql, dom, filter, gd, json, libxml, zip

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Create .env file
        run: |
          cp .env.example .env
          sed -i "s|DB_CONNECTION=.*|DB_CONNECTION=pgsql|g" .env
          sed -i "s|DB_HOST=.*|DB_HOST=127.0.0.1|g" .env
          sed -i "s|DB_PORT=.*|DB_PORT=5432|g" .env
          sed -i "s|DB_DATABASE=.*|DB_DATABASE=laravel_test|g" .env
          sed -i "s|DB_USERNAME=.*|DB_USERNAME=postgres|g" .env
          sed -i "s|DB_PASSWORD=.*|DB_PASSWORD=secret|g" .env
          sed -i "s|REDIS_HOST=.*|REDIS_HOST=127.0.0.1|g" .env
          sed -i "s|REDIS_PASSWORD=.*|REDIS_PASSWORD=null|g" .env
          sed -i "s|REDIS_PORT=.*|REDIS_PORT=6379|g" .env

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run Clear Cache
        run: php artisan config:clear

      - name: Install npm dependencies
        run: npm ci --no-audit --no-progress --silent

      - name: Build client
        run: npm run build

      - name: Run Database Migrations
        run: php artisan migrate --force

      - name: Run Tests
        run: php artisan test
